package skunk.domain;

public enum ControllerState
{
START_GAME, RULES, DISPLAY_RULES, ASK_ADD_PLAYER, ADD_PLAYER, ADD_ANOTHER_PLAYER,
NEW_ROUND, PLAY_ROUND, TAKE_A_TURN, NEXT_PLAYER, FINAL_ROUND, TAKE_FINAL_A_TURN, GAME_OVER,
DONE
}
