package skunk.domain;

public enum ControllerState
{
START_GAME, START_ANSWER, RULES, RULES_ANSWER, DISPLAY_RULES, 
ADD_PLAYER, ADD_PLAYER_NAME, ADD_ANOTHER_PLAYER, ADD_ANOTHE_PLAYER_ANSWER,
PLAY_ROUND,
DONE
}
